# ********RoostGPT********

# Test generated by RoostGPT for test roostKarateAPISpec using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
Feature: Realtime Weather API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: karate.properties['key'] }

  Scenario Outline: Get current weather information with valid parameters
    Given path 'v1/current.json'
    And param q = '<q>'
    And param lang = '<lang>'
    When method GET
    Then status 200
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.current.last_updated_epoch == '#number'
    And match response.current.last_updated == '#string'
    And match response.current.temp_c == '#number'
    And match response.current.temp_f == '#number'
    And match response.current.is_day == '#number'
    And match response.current.condition.text == '#string'
    And match response.current.condition.icon == '#string'
    And match response.current.condition.code == '#number'
    And match response.current.wind_mph == '#number'
    And match response.current.wind_kph == '#number'
    And match response.current.wind_degree == '#number'
    And match response.current.wind_dir == '#string'
    And match response.current.pressure_mb == '#number'
    And match response.current.pressure_in == '#number'
    And match response.current.precip_mm == '#number'
    And match response.current.precip_in == '#number'
    And match response.current.humidity == '#number'
    And match response.current.cloud == '#number'
    And match response.current.feelslike_c == '#number'
    And match response.current.feelslike_f == '#number'
    And match response.current.vis_km == '#number'
    And match response.current.vis_miles == '#number'
    And match response.current.uv == '#number'
    And match response.current.gust_mph == '#number'
    And match response.current.gust_kph == '#number'
    And match response.current.air_quality.co == '#number'
    And match response.current.air_quality.no2 == '#number'
    And match response.current.air_quality.o3 == '#number'
    And match response.current.air_quality.so2 == '#number'
    And match response.current.air_quality.pm2_5 == '#number'
    And match response.current.air_quality.pm10 == '#number'
    And match response.current.air_quality['us-epa-index'] == '#number'
    And match response.current.air_quality['gb-defra-index'] == '#number'

    Examples:
      | read('current.json_get.csv') |

  Scenario: Get current weather information without 'q' parameter
    Given path 'v1/current.json'
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == '#string'

  Scenario: Get current weather information with invalid API key
    * configure headers = { Authorization: 'invalid_key' }
    Given path 'v1/current.json'
    And param q = 'New York'
    When method GET
    Then status 401
    And match response.code == 1002
    And match response.message == '#string'

  Scenario: Get current weather information with disabled API key
    * configure headers = { Authorization: 'disabled_key' }
    Given path 'v1/current.json'
    And param q = 'New York'
    When method GET
    Then status 403
    And match response.code == 2008
    And match response.message == '#string'
