# ********RoostGPT********

# Test generated by RoostGPT for test roostKarateAPISpec using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /forecast.json_get for http method type GET 
# RoostTestHash=d6dc627f87
# 
# 

# ********RoostGPT********
Feature: Forecast Weather API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: karate.properties['key'] }

  Scenario Outline: Validate Forecast Weather API with valid parameters
    Given path 'v1/forecast.json'
    And param q = '<q>'
    And param days = <days>
    And param dt = '<dt>'
    And param unixdt = <unixdt>
    And param hour = <hour>
    And param lang = '<lang>'
    And param alerts = '<alerts>'
    And param aqi = '<aqi>'
    And param tp = <tp>
    When method GET
    Then status 200
    And match response.location.name == '#string'
    And match response.location.region == '#string'
    And match response.location.country == '#string'
    And match response.location.lat == '#number'
    And match response.location.lon == '#number'
    And match response.location.tz_id == '#string'
    And match response.location.localtime_epoch == '#number'
    And match response.location.localtime == '#string'
    And match response.current.last_updated_epoch == '#number'
    And match response.current.last_updated == '#string'
    And match response.current.temp_c == '#number'
    And match response.current.temp_f == '#number'
    And match response.current.is_day == '#number'
    And match response.current.condition.text == '#string'
    And match response.current.condition.icon == '#string'
    And match response.current.condition.code == '#number'
    And match response.current.wind_mph == '#number'
    And match response.current.wind_kph == '#number'
    And match response.current.wind_degree == '#number'
    And match response.current.wind_dir == '#string'
    And match response.current.pressure_mb == '#number'
    And match response.current.pressure_in == '#number'
    And match response.current.precip_mm == '#number'
    And match response.current.precip_in == '#number'
    And match response.current.humidity == '#number'
    And match response.current.cloud == '#number'
    And match response.current.feelslike_c == '#number'
    And match response.current.feelslike_f == '#number'
    And match response.current.vis_km == '#number'
    And match response.current.vis_miles == '#number'
    And match response.current.uv == '#number'
    And match response.current.gust_mph == '#number'
    And match response.current.gust_kph == '#number'
    And match response.current.air_quality.co == '#number'
    And match response.current.air_quality.no2 == '#number'
    And match response.current.air_quality.o3 == '#number'
    And match response.current.air_quality.so2 == '#number'
    And match response.current.air_quality.pm2_5 == '#number'
    And match response.current.air_quality.pm10 == '#number'
    And match response.current.air_quality['us-epa-index'] == '#number'
    And match response.current.air_quality['gb-defra-index'] == '#number'
    And match response.forecast.forecastday[*].date == '#string'
    And match response.forecast.forecastday[*].date_epoch == '#number'
    And match response.forecast.forecastday[*].day.maxtemp_c == '#number'
    And match response.forecast.forecastday[*].day.maxtemp_f == '#number'
    And match response.forecast.forecastday[*].day.mintemp_c == '#number'
    And match response.forecast.forecastday[*].day.mintemp_f == '#number'
    And match response.forecast.forecastday[*].day.avgtemp_c == '#number'
    And match response.forecast.forecastday[*].day.avgtemp_f == '#number'
    And match response.forecast.forecastday[*].day.maxwind_mph == '#number'
    And match response.forecast.forecastday[*].day.maxwind_kph == '#number'
    And match response.forecast.forecastday[*].day.totalprecip_mm == '#number'
    And match response.forecast.forecastday[*].day.totalprecip_in == '#number'
    And match response.forecast.forecastday[*].day.avgvis_km == '#number'
    And match response.forecast.forecastday[*].day.avgvis_miles == '#number'
    And match response.forecast.forecastday[*].day.avghumidity == '#number'
    And match response.forecast.forecastday[*].day.daily_will_it_rain == '#number'
    And match response.forecast.forecastday[*].day.daily_chance_of_rain == '#number'
    And match response.forecast.forecastday[*].day.daily_will_it_snow == '#number'
    And match response.forecast.forecastday[*].day.daily_chance_of_snow == '#number'
    And match response.forecast.forecastday[*].day.condition.text == '#string'
    And match response.forecast.forecastday[*].day.condition.icon == '#string'
    And match response.forecast.forecastday[*].day.condition.code == '#number'
    And match response.forecast.forecastday[*].day.uv == '#number'
    And match response.forecast.forecastday[*].astro.sunrise == '#string'
    And match response.forecast.forecastday[*].astro.sunset == '#string'
    And match response.forecast.forecastday[*].astro.moonrise == '#string'
    And match response.forecast.forecastday[*].astro.moonset == '#string'
    And match response.forecast.forecastday[*].astro.moon_phase == '#string'
    And match response.forecast.forecastday[*].astro.moon_illumination == '#string'
    And match response.forecast.forecastday[*].hour[*].time_epoch == '#number'
    And match response.forecast.forecastday[*].hour[*].time == '#string'
    And match response.forecast.forecastday[*].hour[*].temp_c == '#number'
    And match response.forecast.forecastday[*].hour[*].temp_f == '#number'
    And match response.forecast.forecastday[*].hour[*].is_day == '#number'
    And match response.forecast.forecastday[*].hour[*].condition.text == '#string'
    And match response.forecast.forecastday[*].hour[*].condition.icon == '#string'
    And match response.forecast.forecastday[*].hour[*].condition.code == '#number'
    And match response.forecast.forecastday[*].hour[*].wind_mph == '#number'
    And match response.forecast.forecastday[*].hour[*].wind_kph == '#number'
    And match response.forecast.forecastday[*].hour[*].wind_degree == '#number'
    And match response.forecast.forecastday[*].hour[*].wind_dir == '#string'
    And match response.forecast.forecastday[*].hour[*].pressure_mb == '#number'
    And match response.forecast.forecastday[*].hour[*].pressure_in == '#number'
    And match response.forecast.forecastday[*].hour[*].precip_mm == '#number'
    And match response.forecast.forecastday[*].hour[*].precip_in == '#number'
    And match response.forecast.forecastday[*].hour[*].humidity == '#number'
    And match response.forecast.forecastday[*].hour[*].cloud == '#number'
    And match response.forecast.forecastday[*].hour[*].feelslike_c == '#number'
    And match response.forecast.forecastday[*].hour[*].feelslike_f == '#number'
    And match response.forecast.forecastday[*].hour[*].windchill_c == '#number'
    And match response.forecast.forecastday[*].hour[*].windchill_f == '#number'
    And match response.forecast.forecastday[*].hour[*].heatindex_c == '#number'
    And match response.forecast.forecastday[*].hour[*].heatindex_f == '#number'
    And match response.forecast.forecastday[*].hour[*].dewpoint_c == '#number'
    And match response.forecast.forecastday[*].hour[*].dewpoint_f == '#number'
    And match response.forecast.forecastday[*].hour[*].will_it_rain == '#number'
    And match response.forecast.forecastday[*].hour[*].chance_of_rain == '#number'
    And match response.forecast.forecastday[*].hour[*].will_it_snow == '#number'
    And match response.forecast.forecastday[*].hour[*].chance_of_snow == '#number'
    And match response.forecast.forecastday[*].hour[*].vis_km == '#number'
    And match response.forecast.forecastday[*].hour[*].vis_miles == '#number'
    And match response.forecast.forecastday[*].hour[*].gust_mph == '#number'
    And match response.forecast.forecastday[*].hour[*].gust_kph == '#number'
    And match response.forecast.forecastday[*].hour[*].uv == '#number'
    And match response.alerts.alert[*].headline == '#string'
    And match response.alerts.alert[*].msgtype == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].severity == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].urgency == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].areas == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].category == '#string'
    And match response.alerts.alert[*].certainty == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].event == '#string'
    And match response.alerts.alert[*].note == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].effective == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].expires == '#? _ == null || typeof _ == "string"'
    And match response.alerts.alert[*].desc == '#string'
    And match response.alerts.alert[*].instruction == '#string'

    Examples:
      | read('forecast.json_get.csv') |

  Scenario Outline: Validate Forecast Weather API with missing or invalid parameters
    Given path 'v1/forecast.json'
    And param q = '<q>'
    And param days = <days>
    When method GET
    Then status <status>
    And match response.code == <code>
    And match response.message == '#string'

    Examples:
      | q          | days | status | code |
      | null       |    5 |    400 | 1003 |
      | 'Invalid'  |    5 |    400 | 1006 |
      | 'New York' |   15 |    400 | 1005 |
      | 'New York' |    0 |    400 | 1005 |
