# ********RoostGPT********

# Test generated by RoostGPT for test roostKarateAPISpec using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /search.json_get for http method type GET 
# RoostTestHash=72ffe69306
# 
# 

# ********RoostGPT********
Feature: WeatherAPI Search/Autocomplete API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: karate.properties['key'] }

  Scenario Outline: Validate successful search with valid query parameter
    Given path '/v1/search.json'
    And param q = '<query>'
    When method GET
    Then status 200
    And match response == '#[]'
    And match each response[*].id == '#number'
    And match each response[*].name == '#string'
    And match each response[*].region == '#string'
    And match each response[*].country == '#string'
    And match each response[*].lat == '#number'
    And match each response[*].lon == '#number'
    And match each response[*].url == '#string'

    Examples:
      | read('search.json_get.csv') |

  Scenario: Validate error response when query parameter is missing
    Given path '/v1/search.json'
    When method GET
    Then status 400
    And match response.code == 1003
    And match response.message == '##string'

  Scenario: Validate error response when API key is missing
    * configure headers = {}
    Given path '/v1/search.json'
    And param q = 'London'
    When method GET
    Then status 401
    And match response.code == 1002
    And match response.message == '##string'

  Scenario: Validate error response when API key is invalid
    * configure headers = { Authorization: 'invalid_key' }
    Given path '/v1/search.json'
    And param q = 'London'
    When method GET
    Then status 401
    And match response.code == 2006
    And match response.message == '##string'

  Scenario: Validate error response when API key exceeds quota
    * configure headers = { Authorization: 'exceeded_quota_key' }
    Given path '/v1/search.json'
    And param q = 'London'
    When method GET
    Then status 403
    And match response.code == 2007
    And match response.message == '##string'
