# ********RoostGPT********

# Test generated by RoostGPT for test roostKarateAPISpec using AI Type Open AI and AI Model gpt-4o
# 
# Feature file generated for /timezone.json_get for http method type GET 
# RoostTestHash=df6b1e5ce9
# 
# 

# ********RoostGPT********
Feature: Time Zone API Tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: karate.properties['key'] }

  Scenario Outline: Validate Time Zone API with valid query parameter
    Given path 'v1/timezone.json'
    And param q = '<query>'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.name == '#string'
    And match response.region == '#string'
    And match response.country == '#string'
    And match response.lat == '#number'
    And match response.lon == '#number'
    And match response.tz_id == '#string'
    And match response.localtime_epoch == '#number'
    And match response.localtime == '#string'

    Examples:
      | read('timezone.json_get.csv') |

  Scenario: Validate Time Zone API with missing query parameter
    Given path 'v1/timezone.json'
    When method GET
    Then status 400
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'

  Scenario: Validate Time Zone API with invalid API key
    * configure headers = { Authorization: 'invalid_key' }
    Given path 'v1/timezone.json'
    And param q = 'New York'
    When method GET
    Then status 401
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'

  Scenario: Validate Time Zone API with exceeded quota
    * configure headers = { Authorization: 'exceeded_quota_key' }
    Given path 'v1/timezone.json'
    And param q = 'New York'
    When method GET
    Then status 403
    And match response == '#object'
    And match response.code == '#number'
    And match response.message == '#string'
